const gamesData = [
    {
        id: 1,
        title: "Black Myth: Wukong",
        image: "black-myth-wukong.jpg",
        category: ["action", "rpg", "soulslike"],
        popularity: 98,
        year: 2024,
        description: "Эпический ролевой экшен по мотивам китайской мифологии. Вы играете за Избранного, который отправляется в опасное путешествие, полное сражений с могущественными врагами. Игра сочетает глубокую боевую систему, исследование мира и захватывающий сюжет.",
        login: "oxfph1ww3lw",
        password: "TzcnkWbt7n",
        reports: []
    },
    {
        id: 2,
        title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
        image: "stalker-2.jpg",
        category: ["shooter", "survival", "horror"],
        popularity: 96,
        year: 2024,
        description: "Долгожданное продолжение культовой серии. Отправляйтесь в аномальную Зону отчуждения, полную мутантов, аномалий и враждебных группировок. Нелинейный сюжет, атмосфера постапокалипсиса и выживание в суровых условиях.",
        login: "wilbertlovelace0q",
        password: "sKPzScGqEM1984",
        reports: []
    },
    {
        id: 3,
        title: "Forza Horizon 5",
        image: "forza-horizon-5.jpg",
        category: ["racing", "simulator", "openworld"],
        popularity: 92,
        year: 2021,
        description: "Гоночный симулятор в открытом мире Мексики. Огромный парк автомобилей, динамическая смена погоды, фестивали и соревнования. Исследуйте живописные локации и участвуйте в захватывающих гонках.",
        login: "exqgy03440",
        password: "2eZ9C3s9",
        reports: []
    },
    {
        id: 4,
        title: "RESIDENT EVIL 4",
        image: "resident-evil-4.jpg",
        category: ["horror", "action", "shooter"],
        popularity: 91,
        year: 2023,
        description: "Ремейк легендарного хоррора. Леон Кеннеди отправляется в испанскую деревню спасти дочь президента. Переосмысленная боевая система, напряжённая атмосфера и культовые сражения с Лос-Иллюминадос.",
        login: "exqgy03440",
        password: "2eZ9C3s9",
        reports: []
    },
    {
        id: 5,
        title: "RESIDENT EVIL VILLAGE",
        image: "resident-evil-village.jpg",
        category: ["horror", "action", "shooter"],
        popularity: 89,
        year: 2021,
        description: "Продолжение истории Итана Уинтерса. Восьмая часть переносит действие в загадочную деревню, где обитают вампиры, оборотни и леди Димитреску. Смесь экшена и классического survival-хоррора.",
        login: "exqgy03440",
        password: "2eZ9C3s9",
        reports: []
    },
    {
        id: 6,
        title: "The Witcher 3: Wild Hunt",
        image: "witcher-3.jpg",
        category: ["rpg", "openworld", "action"],
        popularity: 95,
        year: 2015,
        description: "Шедевр от CD Projekt RED. Геральт из Ривии ищет Цири в огромном мире, полном монстров, политических интриг и моральных выборов. Включает дополнения «Каменные сердца» и «Кровь и вино».",
        login: "conrt985",
        password: "gafFykxaaE",
        reports: []
    },
    {
        id: 7,
        title: "Control",
        image: "control.jpg",
        category: ["action", "adventure", "mystic"],
        popularity: 85,
        year: 2019,
        description: "Джесси Фейден приходит в Федеральное Бюро Контроля и обнаруживает, что здание захвачено потусторонней силой. Телекинез, левитация и трансформирующееся оружие — ваши инструменты в борьбе с Иссом.",
        login: "72108fd4",
        password: "Hjy413687",
        reports: []
    },
    {
        id: 8,
        title: "Raft",
        image: "raft.jpg",
        category: ["survival", "adventure", "coop"],
        popularity: 82,
        year: 2022,
        description: "Выживание на плоту в открытом океане. Собирайте мусор, стройте и расширяйте свой плот, исследуйте острова и подводный мир. Можно играть в кооперативе с друзьями.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 9,
        title: "The Forest",
        image: "the-forest.jpg",
        category: ["survival", "horror", "openworld"],
        popularity: 80,
        year: 2018,
        description: "Выживание после авиакатастрофы в лесу, полном каннибалов и мутантов. Стройте убежище, охотьтесь, сражайтесь и исследуйте пещеры в поисках пропавшего сына.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 10,
        title: "Borderlands 3",
        image: "borderlands-3.jpg",
        category: ["shooter", "rpg", "action"],
        popularity: 83,
        year: 2019,
        description: "Лутер-шутер с миллиардами пушек, безумными персонажами и фирменным юмором. Остановите близнецов Калипсо и спасите галактику.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 11,
        title: "Risk of Rain 2",
        image: "risk-of-rain-2.jpg",
        category: ["roguelike", "shooter", "action"],
        popularity: 81,
        year: 2020,
        description: "Рогалик-шутер от третьего лица. Сражайтесь с ордами врагов на инопланетной планете, собирайте предметы усиления и пытайтесь выжить как можно дольше.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 12,
        title: "It Takes Two",
        image: "it-takes-two.jpg",
        category: ["adventure", "coop", "platformer"],
        popularity: 88,
        year: 2021,
        description: "Кооперативное приключение, которое можно пройти только вдвоём. История пары, превращённых в кукол, которые должны заново научиться работать вместе. Разнообразный геймплей и трогательный сюжет.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 13,
        title: "Dying Light",
        image: "dying-light.jpg",
        category: ["horror", "action", "survival", "openworld"],
        popularity: 86,
        year: 2015,
        description: "Зомби-экшен с паркуром. Перемещайтесь по городу Харран, сражайтесь с заражёнными днём и выживайте против особо опасных ночных монстров.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 14,
        title: "Crysis 2",
        image: "crysis-2.jpg",
        category: ["shooter", "action"],
        popularity: 70,
        year: 2011,
        description: "Легендарный шутер в Нью-Йорке. Нанокостюм даёт сверхспособности: невидимость, суперсилу и броню. Сражайтесь с инопланетными захватчиками и коррумпированными военными.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 15,
        title: "Sniper Elite 4",
        image: "sniper-elite-4.jpg",
        category: ["shooter", "stealth", "action"],
        popularity: 75,
        year: 2017,
        description: "Тактический снайперский шутер в Италии времён Второй мировой. Выполняйте миссии скрытно, используя баллистику ветра и пульса, знаменитую X-Ray камеру убийств и окружение.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 16,
        title: "HITMAN 2",
        image: "hitman-2.jpg",
        category: ["stealth", "action", "simulator"],
        popularity: 78,
        year: 2018,
        description: "Симулятор наёмного убийцы. Агент 47 путешествует по миру, устраняя цели самыми изобретательными способами. Огромные песочницы, множество путей и маскировка.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 17,
        title: "Half-Life",
        image: "half-life.jpg",
        category: ["shooter", "classic", "action"],
        popularity: 84,
        year: 1998,
        description: "Культовый шутер, изменивший жанр. Гордон Фримен, учёный-физик, борется с пришельцами из Зена и военными после катастрофы в Чёрной Мезе.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 18,
        title: "Half-Life: Opposing Force",
        image: "half-life-opposing-force.jpg",
        category: ["shooter", "classic", "action"],
        popularity: 72,
        year: 1999,
        description: "Дополнение к оригинальному Half-Life. Играйте за капрала Адриана Шепарда, отправленного в Чёрную Мезу для зачистки. Новая кампания, оружие и враги.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 19,
        title: "Half-Life: Blue Shift",
        image: "half-life-blue-shift.jpg",
        category: ["shooter", "classic", "action"],
        popularity: 69,
        year: 2001,
        description: "Второе дополнение к Half-Life. Охранник Барни Калхун пытается сбежать из захваченной Чёрной Мезы вместе с группой учёных.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 20,
        title: "CS 1.6",
        image: "cs-16.jpg",
        category: ["shooter", "classic", "multiplayer"],
        popularity: 77,
        year: 2000,
        description: "Counter-Strike 1.6 — легендарный многопользовательский шутер, положивший начало киберспорту. Террористы против спецназа, закладка бомб и спасение заложников.",
        login: "bas_suurland@hotmail.com",
        password: "u4r9omZo2MW3L4J",
        reports: []
    },
    {
        id: 21,
        title: "Metro 2033",
        image: "metro-2033.jpg",
        category: ["shooter", "horror", "survival"],
        popularity: 79,
        year: 2010,
        description: "Атмосферный шутер по роману Дмитрия Глуховского. Артём выживает в московском метро после ядерной войны. Сражайтесь с мутантами и враждебными фракциями, экономьте патроны и фильтры.",
        login: "magepll",
        password: "marpanov_free16",
        reports: []
    },
    {
        id: 22,
        title: "Sid Meier's Civilization V",
        image: "civilization-5.jpg",
        category: ["strategy", "simulator", "historical"],
        popularity: 87,
        year: 2010,
        description: "Глобальная пошаговая стратегия. Постройте империю от древности до космической эры. Дипломатия, война, наука и культура — выбирайте путь к мировому господству.",
        login: "arzillo723",
        password: "marpanov_free14",
        reports: []
    },
    {
        id: 23,
        title: "Assetto Corsa",
        image: "assetto-corsa.jpg",
        category: ["racing", "simulator"],
        popularity: 76,
        year: 2014,
        description: "Реалистичный автосимулятор с превосходной физикой. Десятки трасс и автомобилей, поддержка модов и широкая настройка параметров.",
        login: "yromadev1",
        password: "xDvTSb37UyBRsY",
        reports: []
    },
    {
        id: 24,
        title: "Farming Simulator 25",
        image: "farming-simulator-25.jpg",
        category: ["simulator", "relaxing"],
        popularity: 73,
        year: 2024,
        description: "Новейшая часть симулятора фермера. Выращивайте урожай, разводите скот и управляйте сельскохозяйственной техникой в детализированном мире.",
        login: "yromadev1",
        password: "xDvTSb37UyBRsY",
        reports: []
    },
    {
        id: 25,
        title: "Garry's Mod",
        image: "garrys-mod.jpg",
        category: ["sandbox", "simulator", "multiplayer"],
        popularity: 90,
        year: 2006,
        description: "Физическая песочница без ограничений. Спавните объекты, создавайте машины, сцены и целые миры. Тысячи модов и бесконечные возможности для творчества.",
        login: "yromadev1",
        password: "xDvTSb37UyBRsY",
        reports: []
    },
    {
        id: 26,
        title: "Turmoil",
        image: "turmoil.jpg",
        category: ["strategy", "simulator", "relaxing"],
        popularity: 68,
        year: 2016,
        description: "Экономический симулятор нефтяного магната XIX века. Добывайте нефть, продавайте её с выгодой и расширяйте свой бизнес в эпоху нефтяной лихорадки.",
        login: "cwy199611",
        password: "Bejdw89611",
        reports: []
    },
    {
        id: 27,
        title: "MudRunner",
        image: "mudrunner.jpg",
        category: ["simulator", "racing", "openworld"],
        popularity: 74,
        year: 2017,
        description: "Суровый симулятор бездорожья. Управляйте мощными грузовиками, преодолевайте грязь, реки и леса, доставляя грузы в труднодоступные места. Реалистичная физика и полное погружение в условия дикой природы.",
        login: "dionildo3",
        password: "Dhodho23",
        reports: []
    },
    {
        id: 28,
        title: "Euro Truck Simulator 2",
        image: "euro-truck-simulator-2.jpg",
        category: ["simulator", "relaxing", "racing"],
        popularity: 88,
        year: 2012,
        description: "Лучший симулятор дальнобойщика. Путешествуйте по Европе, перевозите грузы, стройте свою транспортную империю и наслаждайтесь видами из кабины. Тысячи километров дорог и реалистичная экономика.",
        login: "dionildo3",
        password: "Dhodho23",
        reports: []
    },
    {
        id: 29,
        title: "Baldur's Gate 3",
        image: "baldurs-gate-3.jpg",
        category: ["rpg", "adventure", "strategy"],
        popularity: 99,
        year: 2023,
        description: "Шедевр от Larian Studios. Эпическая RPG по вселенной Dungeons & Dragons с глубочайшим сюжетом, тактическими пошаговыми боями и полной свободой выбора. Ваши решения меняют всё.",
        login: "IgorJeanPaul",
        password: "wwyKwYRC",
        reports: []
    },
    {
        id: 30,
        title: "Internet Cafe Simulator",
        image: "internet-cafe-simulator.jpg",
        category: ["simulator", "strategy"],
        popularity: 62,
        year: 2019,
        description: "Симулятор управления интернет-кафе. Стройте и развивайте свой бизнес, закупайте оборудование, привлекайте клиентов и справляйтесь с неожиданными проблемами вроде хулиганов и проверок.",
        login: "borankk06",
        password: "wwe876we432",
        reports: []
    },
    {
        id: 31,
        title: "Hogwarts Legacy",
        image: "hogwarts-legacy.jpg",
        category: ["rpg", "action", "adventure", "openworld"],
        popularity: 93,
        year: 2023,
        description: "Действие происходит в мире Гарри Поттера XIX века. Станьте студентом Хогвартса, изучайте заклинания, исследуйте волшебный мир и раскройте древнюю тайну. Полное погружение во вселенную.",
        login: "ay5ej9rm8yi3",
        password: "Ny21qsIRKE",
        reports: []
    },
    {
        id: 32,
        title: "Atomic Heart",
        image: "atomic-heart.jpg",
        category: ["shooter", "action", "rpg"],
        popularity: 87,
        year: 2023,
        description: "Альтернативный СССР, 1955 год. Майор Нечаев расследует сбой на секретном предприятии. Безумный экшен с уникальным визуальным стилем, роботами-мутантами и глубокой системой крафта.",
        login: "mfvmm13938",
        password: "odukh69931",
        reports: []
    },
    {
        id: 33,
        title: "Car Mechanic Simulator 2018",
        image: "car-mechanic-simulator-2018.jpg",
        category: ["simulator", "relaxing"],
        popularity: 71,
        year: 2017,
        description: "Симулятор автомеханика. Ремонтируйте, реставрируйте и тюнингуйте десятки автомобилей. От замены масла до полной переборки двигателя — почувствуйте себя в настоящей мастерской.",
        login: "mfvmm13938",
        password: "odukh69931",
        reports: []
    },
    {
        id: 34,
        title: "Euro Truck Simulator 2 (2)",
        image: "euro-truck-simulator-2-alt.jpg",
        category: ["simulator", "relaxing", "racing"],
        popularity: 88,
        year: 2012,
        description: "Второй аккаунт. Лучший симулятор дальнобойщика. Путешествуйте по Европе, перевозите грузы, стройте свою транспортную империю и наслаждайтесь видами из кабины.",
        login: "mfvmm13938",
        password: "odukh69931",
        reports: []
    },
    {
        id: 35,
        title: "007 First Light",
        image: "007-first-light.jpg",
        category: ["action", "shooter", "stealth"],
        popularity: 55,
        year: 2025,
        description: "Шпионский экшен о молодом Джеймсе Бонде. Выполняйте секретные миссии, используйте гаджеты, скрытность и боевые навыки. Станьте агентом 007.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 36,
        title: "Don't Starve Together",
        image: "dont-starve-together.jpg",
        category: ["survival", "adventure", "coop"],
        popularity: 84,
        year: 2016,
        description: "Мультиплеерная версия культового выживания. Исследуйте странный мир, полный опасностей и магии, собирайте ресурсы, стройте базу и не дайте Тьме поглотить вас.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 37,
        title: "Green Hell",
        image: "green-hell.jpg",
        category: ["survival", "horror", "simulator"],
        popularity: 78,
        year: 2019,
        description: "Реалистичное выживание в амазонских джунглях. Боритесь с голодом, болезнями, хищниками и собственным рассудком. Каждая рана может стать смертельной.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 38,
        title: "Metro Exodus",
        image: "metro-exodus.jpg",
        category: ["shooter", "survival", "horror", "openworld"],
        popularity: 90,
        year: 2019,
        description: "Продолжение культовой серии. Артём и спартанцы покидают московское метро и отправляются в путешествие через постапокалиптическую Россию на поезде «Аврора».",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 39,
        title: "Outlast",
        image: "outlast.jpg",
        category: ["horror", "survival", "stealth"],
        popularity: 83,
        year: 2013,
        description: "Журналист Майлз Апшур проникает в психиатрическую лечебницу Маунт-Мэссив. Без оружия, только камера. Один из самых страшных хорроров в истории.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 40,
        title: "Outlast 2",
        image: "outlast-2.jpg",
        category: ["horror", "survival", "stealth"],
        popularity: 81,
        year: 2017,
        description: "Продолжение легендарного хоррора. Расследование убийства приводит в пустыню Аризоны, где сектанты творят безумные ритуалы. Ещё страшнее, ещё мрачнее.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 41,
        title: "PAYDAY 2",
        image: "payday-2.jpg",
        category: ["shooter", "action", "coop"],
        popularity: 85,
        year: 2013,
        description: "Кооперативный шутер об ограблениях. Соберите команду, спланируйте налёт и сорвите куш. Десятки миссий, масок, оружия и бесконечный адреналин.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 42,
        title: "Portal 2",
        image: "portal-2.jpg",
        category: ["adventure", "puzzle", "action"],
        popularity: 91,
        year: 2011,
        description: "Гениальная головоломка от Valve. Используйте портальную пушку, чтобы решать задачи в лабораториях Aperture Science. Потрясающий сюжет, юмор ГЛэДОС и кооперативный режим.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 43,
        title: "POSTAL 2",
        image: "postal-2.jpg",
        category: ["shooter", "action", "classic"],
        popularity: 67,
        year: 2003,
        description: "Культовый скандальный шутер. Чувак выполняет повседневные дела в городе Парадайз. Можно пройти игру не убив никого, но большинство выбирает другой путь.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 44,
        title: "Middle-earth: Shadow of Mordor",
        image: "shadow-of-mordor.jpg",
        category: ["action", "rpg", "openworld"],
        popularity: 82,
        year: 2014,
        description: "Экшен во вселенной Властелина колец. Играйте за следопыта Талиона, мстите за гибель семьи и используйте силу призрака. Революционная система Nemesis делает каждого врага уникальным.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 45,
        title: "Middle-earth: Shadow of War",
        image: "shadow-of-war.jpg",
        category: ["action", "rpg", "openworld"],
        popularity: 80,
        year: 2017,
        description: "Продолжение Shadow of Mordor. Талион продолжает борьбу с Сауроном, создавая армию орков. Улучшенная система Nemesis, масштабные осады крепостей и новая история.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 46,
        title: "Sea of Thieves",
        image: "sea-of-thieves.jpg",
        category: ["adventure", "action", "coop", "openworld"],
        popularity: 86,
        year: 2018,
        description: "Пиратское приключение в открытом мире. Соберите команду, поднимите паруса и отправляйтесь на поиски сокровищ. Морские сражения, загадочные острова и легендарный квест за пиратской славой.",
        login: "firstlight0067",
        password: "146788firstlight!",
        reports: []
    },
    {
        id: 47,
        title: "Marvel's Spider-Man Remastered",
        image: "marvel-spider-man-remaster.jpg",
        category: ["action", "adventure", "openworld"],
        popularity: 95,
        year: 2022,
        description: "Эталонный экшен от Insomniac Games. Станьте Питером Паркером, который балансирует между жизнью героя и обычного парня. Летайте на паутине по детально проработанному Нью-Йорку, сражайтесь с культом Демонов, Осьминогом и Веномом. Ремастер включает улучшенную графику с трассировкой лучей, всех трёх дополнений и режим производительности.",
        login: "tioclubposneilistala",
        password: "73N6FXT3BNB7",
        reports: []
    },
    {
        id: 48,
        title: "Detroit: Become Human",
        image: "detroit-become-human.jpg",
        category: ["adventure", "mystic", "historical"],
        popularity: 92,
        year: 2020,
        description: "Интерактивная драма от Quantic Dream. Играйте за трёх андроидов - Коннора, Маркуса и Кару - чьи судьбы переплетаются в городе будущего. Каждое ваше решение меняет сюжет, ведёт к гибели героев или революции. Десятки концовок, эмоциональный сюжет о свободе, предрассудках и человечности. Это больше чем игра - это выбор без права на ошибку.",
        login: "class4r",
        password: "classas0002",
        reports: []
    }
];

// ПРИНУДИТЕЛЬНАЯ очистка localStorage (удалить эту строку после первого запуска)
localStorage.removeItem('gamesData');

// Сохраняем свежие данные
localStorage.setItem('gamesData', JSON.stringify(gamesData));

// Грузим из localStorage
const storedData = localStorage.getItem('gamesData');
if (storedData) {
    try {
        const parsed = JSON.parse(storedData);
        gamesData.length = 0;
        parsed.forEach(g => gamesData.push(g));
    } catch(e) {
        console.error('Ошибка загрузки данных из localStorage');
    }
}